package cs230.system;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
/**
 * @author 959470
 *
 */

public class Dvd extends Resource implements Serializable {
	private static final long serialVersionUID = 1L;
	//The director of the Dvd
	private String director;
	//Its Runtime
	private int runtime ;
	//The spoken language of the Dvd
	private String language;
	//The available subLanguages
	private ArrayList<String> subLanguages ;
	
	/**
	 * The constructor of a new Dvd
	 * @param id
	 * @param title
	 * @param year
	 * @param thumbnail
	 * @param director The director of the Dvd
	 * @param runtime Its Runtime
	 * @param language The spoken language of the Dvd
	 * @param subLanguages The available subLanguages
	 */
	public Dvd (int id, String title , int year, String thumbnail , String director , int runtime ,String language ,ArrayList<String> subLanguages) {
		super(id,title,year,thumbnail);
		this.director=director;
		this.runtime=runtime;
		this.language=language;
		this.subLanguages=subLanguages;
		this.type = "Dvd";
		create();
	}
	
	
	/**
	 * Sets the director
	 * @param director
	 */
	public  void setDirector (String director) {
		this.director=director;
		this.update();
	}
	/**
	 * Sets the runtime
	 * @param runtime
	 */
	public  void setRuntime (int runtime) {
		this.runtime=runtime;
		this.update();
	}
	/**
	 * Sets the spoken language
	 * @param language
	 */
	public  void setLanguage (String language) {
		this.language=language;
		this.update();
	}
	/**
	 * Sets the subLanguages
	 * @param subLanguages
	 */
	public  void setSubLanguages (ArrayList<String> subLanguages) {
		this.subLanguages=subLanguages;
		this.update();
	}
	
	/**
	 * @return The director
	 */
	public  String getDirector () {
		return this.director;
	}
	/**
	 * @return The runtime
	 */
	public  int getRuntime () {
		return this.runtime;
	}
	/**
	 * @return The spoken language
	 */
	public  String getLanguage () {
		return this.language;
	}
	/**
	 * @return The list of subLanguages
	 */
	public  ArrayList<String> getSubLanguages () {
		return this.subLanguages;
	}
	
	/**
	 * Updates a specific attribute in the Dvd table of the Database
	 * @param field The field that will be updated
	 * @param attribute The new value of the attribute
	 */
	@Override
	public void update () {
		DatabaseManager.editRecord(this.getID(),this,"Dvd");
	}
	
	/** 
	 * Creates a new entry in the database for a new Dvd 
	 */
	public void create () {
		DatabaseManager.saveRecord(this,"Dvd");
		DatabaseManager.saveRecord(this.id,"ResourceIDs");
	
	}
	
	/**
	 * Deletes all the information associated with this Dvd from the Database
	 */
	public void delete () {
		DatabaseManager.deleteRecord(this,"Dvd");
		DatabaseManager.deleteRecord(this.id,"ResourceIDs");
	}
	
	/** 
	 * Overrides the defauls equeals method so that if any of the attributes of a Dvd are the same as another, then it returns true 
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		
		Dvd dvd = (Dvd) obj;

		if (this.director.equalsIgnoreCase(dvd.director)) {
			return true;
		}
		
		if (this.title.equalsIgnoreCase(dvd.title)) {
			return true;
		}

		if (this.id == dvd.id) {
			return true;
		}

		if (this.year == dvd.year) {
			return true;
		}
		
		if (this.runtime == dvd.runtime) {
			return true;
		}

		if (this.language.equalsIgnoreCase(dvd.language)) {
			return true;
		}
		
		for (String subtitle1 : this.subLanguages) {
		    for (String subtitle2 : dvd.subLanguages) {
		    	if (subtitle1.equalsIgnoreCase(subtitle2)){
		    		return true;
		    	}
		    }
		}

		return false;
	}
	
	/**
	 * Takes the string representation of an ArrayList generated by the default toString() method and constructs the ArrayList
	 * @param x the string representation of the arraylist generated by the default toString() method
	 * @return the constructed ArrayList<String>
	 */
//	public  ArrayList<String> toArray (String x){
//		x=x.replaceAll("\\s+","");
//		x=x.substring(1, x.length()-1);
//		String[] subArray = x.split(",");
//		ArrayList<String> subLang = new ArrayList<String>(); 
//		int i=0;
//		
//		while ( i != (subArray.length)) {
//			subLang.add(subArray[i]);
//			i++;
//		}
//		return subLang;
//	}

}
